### ISSUE TITLE
UTF8 problem on Heroku

### ISSUE THREAD

**Issue by Eschon** [mudge/riveted#2]
I have a compojure app that uses this library to parse xml files.
One of the files contains copyright information. When I test it locally everything works fine, but after deploying my app to Heroku the copyright symbol turns into a '?'.

I've confirmed that the copyright symbol appears alright when I read the xml as a string, but after I parse it with riveted it turns into a '?'.

Do you have any idea why this only happens once I deploy to Heroku and do you have a workaround or an idea to fix this?

**Comment by mudge** [comment]
Hi Egon,

Can you tell me a little more about the environments you're seeing this behaviour in? e.g. Clojure version, Java version, operating system, riveted version?

Also could you share some sample code that exhibits this behaviour, e.g. is the following enough to trigger it?

```clojure
(require '[riveted.core :as vtd])
(vtd/text (vtd/navigator "<a>©</a>"))
```

**Comment by Eschon** [comment]
Hi,

Thanks for the fast answer.
Here's the information that you requested:

Clojure Version: 1.8.0
riveted version: 0.0.9
Java Version: 1.8

Unfortunately I couldn't figure out what OS the Clojure buildpack on Heroku is using.

I extracted the code that causes the Problem, but I'll also try your simple example and report back to you.

```clojure
(:require [riveted.core :refer [at navigator search text]])

(let [xml (-> "XMLURL" http/get :body navigator)]
  (println (text (at xml "XPATH"))))
```

**Comment by Eschon** [comment]
I just tested your example and it triggers the problem.

**Comment by mudge** [comment]
I haven't tried it but could it be related to this: "[Default Charset on Heroku (US-ASCII) causing problems](http://stackoverflow.com/questions/16106076/default-charset-on-heroku-us-ascii-causing-problems)"?

**Comment by Eschon** [comment]
This could be the problem.
I left work already so I'll try it tomorrow and report back to you.
Thanks for looking into this.

**Comment by Eschon** [comment]
I've just tested this. The problem was that I was setting the `JAVA_TOOL_OPTIONS` config variable. So the default value that sets the encoding to UTF-8 was overwritten.

Now I just need to find a way to set it in a way that works and doesn't crash my app.
Thanks again for looking into this.
